version: '3.8'
services:
  nest-app:
    build:
      context: ./
      dockerfile: ./Dockerfile
    depends_on:
      - mysql-container
      - redis-container
    ports:
      - 3100:3100
    networks:
      - common-network
  mysql-container:
    image: mysql
    volumes:
      - /Users/xuguowei/mysql-data:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: cancer_hospital
      MYSQL_ROOT_PASSWORD: xgw
    networks:
      - common-network
  redis-container:
    image: redis
    volumes:
      - /Users/xuguowei/redis-data:/data
    ports:
      - 6379:6379
    networks:
      - common-network
networks:
  common-network:
    driver: bridge
